/*
 * content.js - all patient-facing text in English and Dutch.
 *
 * Written for low health literacy: short sentences, plain words, one idea per line.
 * Evidence base: pain neuroscience education plus "stay active" first-line guidance
 * for chronic non-specific low back pain.
 */
window.CONTENT = {
  en: {
    ui: {
      brand: "Back on Track",
      tagline: "Move with confidence, stay independent.",
      hello: "Hello",
      whatNeed: "What do you need?",
      howFeel: "How is your back today?",
      moved: {
        one: "You moved on 1 day this week.",
        many: "You moved on {n} days this week.",
        incToday: " Including today.",
      },
      install: { text: "Add this to your home screen so it is always one tap away.", add: "Add", ios: "To keep the app and your progress, tap the Share button then 'Add to Home Screen'." },
      tiles: {
        today: { t: "Move", s: "Today's exercises" },
        learn: { t: "Understand", s: "Hurt isn't harm" },
        flare: { t: "Bad day", s: "Your flare-up plan" },
        goal: { t: "Your goal", s: "Remember your why" },
        safety: { t: "When to get checked", s: "Warning signs" },
      },
      nav: { home: "Home", today: "Move", learn: "Learn", goal: "Goal" },
      header: { today: "Move", learn: "Understand", flare: "Bad day", goal: "Your goal", safety: "Get checked", progress: "My progress" },
      goalPinned: { label: "My goal", empty: "Tap to set the reason you are doing this" },
      today: {
        title: "Move a little, often",
        intro: "Gentle is good. Do what you can today, even a few movements help. Hold a chair if you feel unsteady, and use a bed if the floor is hard. When one feels easy, do a few more.",
        progress: "{d} of {t} done today",
        complete: ". Nice work.",
        markDone: "Mark as done",
        done: "Done",
      },
      learn: {
        title: "Hurt isn't harm",
        intro: "A few simple ideas that can change how your back feels. Tap a card to open it.",
      },
      flare: { title: "Bad day? You have a plan", tryThis: "Try this", easyRoutine: "Your easy routine", openIt: "Open it" },
      goal: {
        title: "Remember your why",
        intro: "What do you want to get back to? Pick one, or write your own. It will sit on your home screen to keep you going.",
        placeholder: "I want to...",
        save: "Save my goal",
        saved: "Goal saved",
        cleared: "Goal cleared",
      },
      safety: { title: "When to get checked" },
      progress: {
        link: "My progress",
        title: "My progress",
        intro: "A simple summary you can show or send to your physiotherapist.",
        activeDays: "Exercise days",
        thisWeek: "this week",
        exercises: "Exercises done",
        feeling: "How you felt (last 7 days)",
        goalLabel: "Your goal",
        range: "From {from} to {to}",
        none: "No activity yet. Come back after a few days of exercises.",
        share: "Share with my physio",
        copied: "Copied. Paste it to your physio.",
        clear: "Clear my data",
        clearConfirm: "This clears your goal, exercises and check-ins from this browser. Continue?",
        cleared: "Progress cleared",
        privacy: "This stays on your phone until you choose to share it.",
        shareTitle: "Back on Track progress",
      },
      toastMagnet: "Opened from your magnet.",
      disclaimer:
        "This app is for older adults with long-term back pain who worry that moving will cause harm, after a clinician has checked it. It supports, but does not replace, your physiotherapist or doctor. If you feel worse or worried, talk to them.",
      langName: "EN",
      switchTitle: "Schakel naar Nederlands",
    },
    exercises: [
      { id: "pelvic-tilt", name: "Pelvic tilts", cue: "Lie on your back, knees bent. Gently flatten your back into the floor, then relax.", reps: "10 slow times", why: "Wakes up your low back and tummy muscles." },
      { id: "knee-to-chest", name: "Knee to chest", cue: "Lie down. Pull one knee gently toward your chest. Hold for a breath, then swap. Stop if pain spreads down your leg.", reps: "5 each leg", why: "Eases tight muscles in your low back." },
      { id: "cat-camel", name: "Cat and camel", cue: "On hands and knees, slowly arch your back up like a cat, then let it dip down.", reps: "10 slow times", why: "Helps your back move freely." },
      { id: "glute-bridge", name: "Bridge", cue: "Lie on your back, knees bent. Lift your hips up, squeeze, then lower slowly.", reps: "10 times", why: "Builds strong hip and back muscles." },
      { id: "bird-dog", name: "Bird dog", cue: "On hands and knees, reach one arm forward and the opposite leg back. Hold, then swap. Too hard? Move just the arm, or just the leg.", reps: "5 each side", why: "Teaches your back to stay steady." },
      { id: "walk", name: "Go for a walk", cue: "A short, easy walk. Start with what feels okay and build up a little each week.", reps: "5 to 10 minutes", why: "Walking is one of the best things for your back." },
    ],
    lessons: [
      { id: "hurt-harm", title: "Hurt isn't harm", body: "Your pain is real. But pain is your body's alarm, and an alarm can be too sensitive. Hurting does not always mean new damage. A sore back can still be a strong, healthy back." },
      { id: "fear-less", title: "Less fear, more life", body: "When back pain makes you afraid to move, you do less, and your back and legs get weaker. Everyday things get harder and your world gets smaller. Gentle movement, a little at a time, breaks this cycle and helps you stay independent." },
      { id: "strong-back", title: "Your back is strong", body: "Your spine is one of the strongest parts of your body. It is built to bend, lift and move every day." },
      { id: "movement-medicine", title: "Movement is medicine", body: "Moving gently feeds your back and helps it settle. Start small and build up slowly, pace yourself and do not push through sharp pain. Resting too long can make pain last longer." },
      { id: "more-than-back", title: "More than your back", body: "Poor sleep, stress and worry can turn the pain up. This is not your fault and the pain is not imaginary. Good sleep, calm and staying active can turn it down." },
      { id: "flares-normal", title: "Flare-ups are normal", body: "Most people get bad days now and then. A flare-up does not mean you have hurt yourself again. It will settle." },
    ],
    flare: {
      reassure: "This will pass. A bad day does not mean you have done any damage.",
      steps: [
        "Keep moving gently. Try not to stay in bed.",
        "Do the easy routine below.",
        "Use heat: a warm shower or a heat pack can relax your muscles.",
        "Slow your day down, but keep doing small bits of activity.",
        "Breathe slowly and let your shoulders and back relax.",
      ],
      gentleRoutine: ["pelvic-tilt", "knee-to-chest", "walk"],
      seekHelp: "If it does not start to settle within a couple of weeks, or you notice any warning sign, open the red 'When to get checked' card.",
    },
    redFlags: {
      intro: "Most back pain is not dangerous and gets better. But some signs need fast medical help. Get checked straight away if you notice any of these:",
      flags: [
        "You cannot control your pee or poo, you struggle to start peeing, or you cannot feel when you need the toilet.",
        "Numbness or tingling between your legs, around your bottom, or your private area.",
        "New or worsening weakness or numbness in one or both legs, or a foot that drags when you walk.",
        "Sudden, severe, tearing back pain spreading to your belly, with feeling faint or sweaty.",
        "Back pain after a fall or accident, or even a small knock or lift if you are older, have thin bones, or take steroid tablets.",
        "You have or have had cancer and now have new or changing back pain.",
        "Fever, feeling very unwell, or losing weight without trying.",
        "Strong pain at night that will not ease.",
      ],
      action: "If you have a bladder or bowel problem, numbness between your legs, leg weakness, or sudden tearing pain, treat it as an emergency: call 112 or the out-of-hours GP (huisartsenpost) now. For the other signs, see your GP (huisarts) soon.",
      cantCatch: "This list cannot catch everything. If something feels seriously wrong, get checked anyway. And even without these signs, see your GP if your back pain does not improve in about 6 weeks or keeps getting worse.",
    },
    goalPrompts: ["Play with my grandchildren", "Walk to the shops on my own", "Get up from my chair easily", "Get back to gardening", "Sleep through the night", "Keep living in my own home"],
    feelFaces: [
      { value: 0, mark: "0", label: "Awful" },
      { value: 1, mark: "1", label: "Sore" },
      { value: 2, mark: "2", label: "Okay" },
      { value: 3, mark: "3", label: "Good" },
      { value: 4, mark: "4", label: "Great" },
    ],
  },

  nl: {
    ui: {
      brand: "Back on Track",
      tagline: "Beweeg met vertrouwen, blijf zelfstandig.",
      hello: "Hallo",
      whatNeed: "Wat heb je nodig?",
      howFeel: "Hoe gaat het met je rug vandaag?",
      moved: {
        one: "Je hebt deze week op 1 dag bewogen.",
        many: "Je hebt deze week op {n} dagen bewogen.",
        incToday: " Ook vandaag.",
      },
      install: { text: "Zet dit op je beginscherm, zo is het altijd één tik weg.", add: "Toevoegen", ios: "Om de app en je voortgang te bewaren: tik op Delen en dan 'Zet op beginscherm'." },
      tiles: {
        today: { t: "Bewegen", s: "Oefeningen van vandaag" },
        learn: { t: "Begrijpen", s: "Pijn is geen schade" },
        flare: { t: "Slechte dag", s: "Je opvlamming-plan" },
        goal: { t: "Jouw doel", s: "Weet weer waarom" },
        safety: { t: "Wanneer naar de dokter", s: "Waarschuwingstekens" },
      },
      nav: { home: "Start", today: "Bewegen", learn: "Leren", goal: "Doel" },
      header: { today: "Bewegen", learn: "Begrijpen", flare: "Slechte dag", goal: "Jouw doel", safety: "Naar de dokter", progress: "Mijn voortgang" },
      goalPinned: { label: "Mijn doel", empty: "Tik om in te stellen waarom je dit doet" },
      today: {
        title: "Beweeg een beetje, vaak",
        intro: "Rustig is goed. Doe wat je vandaag kunt, ook een paar bewegingen helpen. Houd een stoel vast als je je onzeker voelt, en gebruik een bed als de vloer lastig is. Als iets makkelijk voelt, doe er dan een paar meer.",
        progress: "{d} van {t} gedaan vandaag",
        complete: ". Goed gedaan.",
        markDone: "Markeer als gedaan",
        done: "Gedaan",
      },
      learn: {
        title: "Pijn is geen schade",
        intro: "Een paar simpele ideeën die kunnen veranderen hoe je rug voelt. Tik op een kaart om hem te openen.",
      },
      flare: { title: "Slechte dag? Je hebt een plan", tryThis: "Probeer dit", easyRoutine: "Je rustige routine", openIt: "Open het" },
      goal: {
        title: "Weet weer waarom",
        intro: "Wat wil je weer kunnen doen? Kies er één, of schrijf je eigen. Het komt op je beginscherm om je te motiveren.",
        placeholder: "Ik wil...",
        save: "Bewaar mijn doel",
        saved: "Doel bewaard",
        cleared: "Doel gewist",
      },
      safety: { title: "Wanneer naar de dokter" },
      progress: {
        link: "Mijn voortgang",
        title: "Mijn voortgang",
        intro: "Een eenvoudig overzicht dat je aan je fysiotherapeut kunt laten zien of sturen.",
        activeDays: "Oefendagen",
        thisWeek: "deze week",
        exercises: "Oefeningen gedaan",
        feeling: "Hoe je je voelde (laatste 7 dagen)",
        goalLabel: "Jouw doel",
        range: "Van {from} tot {to}",
        none: "Nog geen activiteit. Kom terug na een paar dagen oefeningen.",
        share: "Deel met mijn fysio",
        copied: "Gekopieerd. Plak het naar je fysio.",
        clear: "Wis mijn gegevens",
        clearConfirm: "Dit wist je doel, oefeningen en check-ins uit deze browser. Doorgaan?",
        cleared: "Voortgang gewist",
        privacy: "Dit blijft op je telefoon totdat je het zelf deelt.",
        shareTitle: "Back on Track voortgang",
      },
      toastMagnet: "Geopend via je magneet.",
      disclaimer:
        "Deze app is voor oudere mensen met langdurige rugpijn die bang zijn dat bewegen schade veroorzaakt, nadat een zorgverlener het heeft nagekeken. Hij ondersteunt je fysiotherapeut of dokter, maar vervangt hen niet. Als je je slechter voelt of zorgen hebt, bespreek het dan met hen.",
      langName: "NL",
      switchTitle: "Switch to English",
    },
    exercises: [
      { id: "pelvic-tilt", name: "Bekkenkanteling", cue: "Lig op je rug, knieën gebogen. Druk je onderrug zachtjes in de vloer, ontspan dan.", reps: "10 keer rustig", why: "Maakt je onderrug- en buikspieren wakker." },
      { id: "knee-to-chest", name: "Knie naar borst", cue: "Lig op je rug. Trek één knie zachtjes naar je borst. Houd even vast, wissel dan. Stop als de pijn verder je been in trekt.", reps: "5 per been", why: "Ontspant strakke spieren in je onderrug." },
      { id: "cat-camel", name: "Kat en kameel", cue: "Op handen en knieën: maak langzaam een bolle rug omhoog, laat hem dan zakken.", reps: "10 keer rustig", why: "Helpt je rug soepel te bewegen." },
      { id: "glute-bridge", name: "Bruggetje", cue: "Lig op je rug, knieën gebogen. Til je heupen op, knijp, en zak langzaam terug.", reps: "10 keer", why: "Bouwt sterke heup- en rugspieren op." },
      { id: "bird-dog", name: "Vogelhond", cue: "Op handen en knieën: strek één arm naar voren en het andere been naar achteren. Houd vast, wissel dan. Te moeilijk? Beweeg alleen de arm, of alleen het been.", reps: "5 per kant", why: "Leert je rug stabiel te blijven." },
      { id: "walk", name: "Maak een wandeling", cue: "Een korte, rustige wandeling. Begin met wat goed voelt en bouw langzaam op.", reps: "5 tot 10 minuten", why: "Wandelen is een van de beste dingen voor je rug." },
    ],
    lessons: [
      { id: "hurt-harm", title: "Pijn is geen schade", body: "Je pijn is echt. Maar pijn is het alarm van je lichaam, en een alarm kan te gevoelig zijn. Pijn betekent niet altijd nieuwe schade. Een pijnlijke rug kan nog steeds een sterke, gezonde rug zijn." },
      { id: "fear-less", title: "Minder angst, meer leven", body: "Als rugpijn je bang maakt om te bewegen, doe je minder en worden je rug en benen zwakker. Dagelijkse dingen worden moeilijker en je wereld wordt kleiner. Rustig bewegen, beetje bij beetje, doorbreekt deze cirkel en helpt je zelfstandig te blijven." },
      { id: "strong-back", title: "Je rug is sterk", body: "Je ruggengraat is een van de sterkste delen van je lichaam. Hij is gemaakt om te buigen, tillen en bewegen." },
      { id: "movement-medicine", title: "Bewegen is medicijn", body: "Rustig bewegen voedt je rug en helpt hem tot rust te komen. Begin klein en bouw langzaam op, doseer en ga niet door felle pijn heen. Te lang rusten kan de pijn juist langer laten duren." },
      { id: "more-than-back", title: "Meer dan je rug", body: "Slecht slapen, stress en zorgen kunnen je pijn versterken. Dit is niet jouw schuld en de pijn is niet ingebeeld. Goede slaap, rust en bewegen kunnen hem verminderen." },
      { id: "flares-normal", title: "Opvlammingen zijn normaal", body: "Bijna iedereen heeft af en toe een slechte dag. Een opvlamming betekent niet dat je jezelf opnieuw bezeerd hebt. Het zakt weer." },
    ],
    flare: {
      reassure: "Dit gaat voorbij. Een slechte dag betekent niet dat je schade hebt aangericht.",
      steps: [
        "Blijf rustig bewegen. Probeer niet in bed te blijven.",
        "Doe de rustige routine hieronder.",
        "Gebruik warmte: een warme douche of een warmtekompres ontspant je spieren.",
        "Doe het rustiger aan, maar blijf kleine dingen doen.",
        "Adem langzaam en laat je schouders en rug ontspannen.",
      ],
      gentleRoutine: ["pelvic-tilt", "knee-to-chest", "walk"],
      seekHelp: "Zakt het niet binnen een paar weken, of merk je een waarschuwingsteken? Open dan de rode kaart 'Wanneer naar de dokter'.",
    },
    redFlags: {
      intro: "De meeste rugpijn is niet gevaarlijk en gaat over. Maar sommige signalen hebben snel medische hulp nodig. Laat je meteen nakijken als je een van deze dingen merkt:",
      flags: [
        "Je kunt je plas of ontlasting niet ophouden, je komt moeilijk op gang met plassen, of je voelt niet wanneer je naar de wc moet.",
        "Een doof gevoel of tintelingen tussen je benen, rond je zitvlak of je geslachtsdelen.",
        "Nieuwe of toenemende zwakte of een doof gevoel in een of beide benen, of een voet die sleept.",
        "Plotselinge, hevige, scheurende rugpijn die naar je buik trekt, met een licht of zweterig gevoel.",
        "Rugpijn na een val of ongeluk, of zelfs na een kleine stoot of tilbeweging als je ouder bent, zwakke botten hebt, of prednison gebruikt.",
        "Je hebt of had kanker en nu nieuwe of veranderende rugpijn.",
        "Koorts, je erg ziek voelen, of afvallen zonder reden.",
        "Hevige pijn 's nachts die niet zakt.",
      ],
      action: "Heb je een probleem met plassen of ontlasting, een doof gevoel tussen je benen, zwakte in een been, of plotselinge scheurende pijn? Behandel dat als een noodgeval: bel 112 of de huisartsenpost nu. Bij de andere signalen: ga snel naar je huisarts.",
      cantCatch: "Deze lijst kan niet alles vangen. Voelt er iets ernstig mis? Laat je dan toch nakijken. En ook zonder deze signalen: ga naar je huisarts als je rugpijn na ongeveer 6 weken niet beter is of steeds erger wordt.",
    },
    goalPrompts: ["Spelen met mijn kleinkinderen", "Zelf naar de winkel lopen", "Makkelijk uit mijn stoel opstaan", "Weer kunnen tuinieren", "Doorslapen 's nachts", "Zelfstandig in mijn eigen huis blijven wonen"],
    feelFaces: [
      { value: 0, mark: "0", label: "Slecht" },
      { value: 1, mark: "1", label: "Pijnlijk" },
      { value: 2, mark: "2", label: "Gaat wel" },
      { value: 3, mark: "3", label: "Goed" },
      { value: 4, mark: "4", label: "Top" },
    ],
  },
};
